# Generated by Django 5.1.3 on 2024-11-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyect',
            old_name='created_at',
            new_name='Creado_en',
        ),
        migrations.RenameField(
            model_name='proyect',
            old_name='technology',
            new_name='Proyecto',
        ),
        migrations.RemoveField(
            model_name='proyect',
            name='description',
        ),
        migrations.RemoveField(
            model_name='proyect',
            name='title',
        ),
        migrations.AddField(
            model_name='proyect',
            name='Apellido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proyect',
            name='Nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proyect',
            name='Rut',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
